// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtolWVbdPiNjFu7dR3SuHFg430BCov_hg',
    appId: '1:1024533370711:web:f4cd49217f93f1cab71012',
    messagingSenderId: '1024533370711',
    projectId: 'fitbody-app-5de4d',
    authDomain: 'fitbody-app-5de4d.firebaseapp.com',
    storageBucket: 'fitbody-app-5de4d.firebasestorage.app',
    measurementId: 'G-HG6PW8DCNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe-8XQpAmPWlYVCd8gT7xg6c8h_oocO7M',
    appId: '1:1024533370711:android:971fbc12d894d381b71012',
    messagingSenderId: '1024533370711',
    projectId: 'fitbody-app-5de4d',
    storageBucket: 'fitbody-app-5de4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXLS6WaDOmVYAnTj7qetylKJDs1iQntE8',
    appId: '1:1024533370711:ios:01294e45ce56c54eb71012',
    messagingSenderId: '1024533370711',
    projectId: 'fitbody-app-5de4d',
    storageBucket: 'fitbody-app-5de4d.firebasestorage.app',
    iosBundleId: 'com.example.fitbodyApp',
  );
}
